# Generated by Django 4.2.7 on 2024-05-22 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vihicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(max_length=50)),
                ('fuel', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('number', models.IntegerField(max_length=50)),
            ],
        ),
    ]
